### ISSUE TITLE
Hang upon creating new singleplayer world

### ISSUE THREAD

**Issue by medavox** [Hugobros3/chunkstories#18] opened 2020-01-23 00:46 UTC
```
Exception in thread "Main thread" java.lang.Exception: Unimplemented system on this backend: interface xyz.chunkstories.api.graphics.systems.dispatching.DefferedLightsRenderer
	at xyz.chunkstories.graphics.opengl.OpenglGraphicsBackend.getOrCreateDispatchingSystem(OpenglGraphicsBackend.kt:176)
	at xyz.chunkstories.graphics.opengl.graph.OpenglPass.<init>(OpenglPass.kt:63)
	at xyz.chunkstories.graphics.opengl.graph.OpenglRenderTask.<init>(OpenglRenderTask.kt:20)
	at xyz.chunkstories.graphics.opengl.graph.OpenglRenderGraph.<init>(OpenglRenderGraph.kt:25)
	at xyz.chunkstories.graphics.opengl.OpenglGraphicsBackend.drawFrame(OpenglGraphicsBackend.kt:145)
	at xyz.chunkstories.graphics.GraphicsEngineImplementation.renderGame(GraphicsEngineImplementation.kt:57)
	at xyz.chunkstories.client.ClientImplementation.mainLoop(ClientImplementation.kt:134)
	at xyz.chunkstories.client.ClientImplementation.<init>(ClientImplementation.kt:116)
	at xyz.chunkstories.client.ClientImplementation$Companion.main(ClientImplementation.kt:189)
	at xyz.chunkstories.client.ClientImplementation.main(ClientImplementation.kt)

```

Built on my machine from the following commits:

repo | commit
-------|------
chunkstories | c0ff1ac0109ce9409ee634039608734936e28240
core              | 2c2a4bb14fdbc6336fc0d7fd9cba3a9709ee58bf
api                | 20c4620fed5fae3f5c72236a938ca13ccb07b76d

my JRE version:
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

my JDK version:  `javac 1.8.0_102`

My OS: 
```
Linux Mint 18.3 Sylvia
(Based on Ubuntu 16.04 LTS Xenial Xerus)
```

Game was run using this command:
```
java -Djava.awt.headless=true -Xmx2G -jar client/build/libs/chunkstories.jar --backend=OPENGL --core=../chunkstories-core/res/
```
, because java complained that `Unrecognized option: -XstartOnFirstThread`

**Comment by Hugobros3** [comment] 2020-01-23 20:45
Duplicate of https://github.com/Hugobros3/chunkstories/issues/13 Will fix when I merge the vulkan renderer improvements I'm working on (branch "farterrain" and "dev" in api), in the meantime you can just work arround the issue like in https://github.com/dector/chunkstories/commit/5053f48414121e1314a0b4cdf597a50a6e461e23

**Comment by Hugobros3** [comment] 2020-01-23 20:46
Does Vulkan not work for you ? It's definitely the better backend with the most work put into it, GL is mostly a fallback path

**Comment by Hugobros3** [comment] 2020-01-26 22:16
"fixed" (workarround discussed in the other issue implemented) in https://github.com/Hugobros3/chunkstories/commit/03e842bfddd2e833a693988e0fe9af42579e0b99#diff-af38d8f2f439ab601d2da9bd029e8f36R62

**Comment by Hugobros3** [comment] 2020-01-26 22:16
closing this issue because dup and #13 will be left open for tracking the underlying issue

**Closed as completed by Hugobros3** 2020-01-26 22:16 UTC
